language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-bagle-component' ]; then cd .. && eval "mv $currentfolder generator-bagle-component" && cd generator-bagle-component; fi

